config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'checkout/create'
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: "products#index"
  root to: "products#list"
  resources :products do
    resources :comments
    resources :reviews
  end
  mount ActionCable.server => '/cable'
  resources :carts
  resources :order_details
  resources :categories
  #resources :checkout
  post "checkout/create", to: "checkout#create"
  get "/search", to: "products#search"
  resources :orders
  resources :about 
  
end

app/models/article.rb
class Article < ApplicationRecord
	 belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5
  belongs_to :product
  belongs_to :user
  # after_create_commit { RenderCommentJob.perform_later self }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 6
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reviews
  has_many :order_details
  has_many :orders, :through => :order_details
  mount_uploaders :avatars, AvatarUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :orders
  has_many :comments
  has_many :reviews
  has_many :products
  enum user_type: {
    moderator: 0,
    buyer: 1
  }
  validates :name, :phone, :user_type, presence: true
  validates :phone, length: { maximum: 10 }
  validates :phone, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!

	def index
		@carts = session[:cart]
	end

	def show
	end

	def new
		
	end

	def edit
		
	end

	def create
		@order_quantity = params[:cart][:addquantity].to_i
		@product_id = params[:cart][:product].to_i
        if session[:cart].select {|cart| cart["product_id"] == @product_id}.present?
        	session[:cart].find{|cart| cart["product_id"] == @product_id}["quantity"] += @order_quantity
			redirect_to carts_path
		else
			ensure_cart_exists << {quantity: @order_quantity, product_id: @product_id}
			redirect_to carts_path
		end
	end

	def update
		@product_id = params[:id].to_i
		@order_quantity = params[:cart][:addquantity].to_i
		@updated_qty = session[:cart].find{|cart| cart["product_id"] == @product_id}["quantity"] - @order_quantity
		@prd_price = params[:cart][:prod_price].to_i
		@updtd_bill = params[:cart][:ttl_bill].to_i
        if session[:cart].select {|cart| cart["product_id"] == @product_id}.present?
        	session[:cart].find{|cart| cart["product_id"] == @product_id}["quantity"] = @order_quantity
			respond_to do |format|
			    format.js { render 'index.js.erb' }
			    format.html { redirect_to carts_path }
			end
		end
	end

	def destroy
		@product_id = params[:id].to_i
		session[:cart].delete_if {|cart| cart["product_id"] == @product_id}
		redirect_to carts_path
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <h5 style="color:green">One new Item has been added to your Cart</h5>
    <div class="col-lg-7" style="border-style: solid; border-width: 1px; border-color: blue; color: black;">
      <% @totl_crt = 0 %>
      <% @total_bill = 0 %>
      <% @total_quantity = 0 %>
      <% @carts.each do |cart| %>
      <% product = Product.find_by(id: cart["product_id"]) %>
      <div class="row" style="background-color: white;">
        <div class="col-lg-2 d-flex align-items-center">
          <% if product.avatars[0].nil? %>
              <p>Image not available</p>
          <% else %>
              <%= image_tag product.avatars[0].url, size: '80x100' %>
          <% end %>
        </div>
        <div class="col-lg-6" id="pro-des">
          <h3><%= product.name %></h3><br>
          <h6 style="color:orangered;">Price: $<%= product.price %>.00 only</h6><br>
          <h6>Quantity: <span class="cart_qty" data-id = "<%=product.id%>" > <%= cart["quantity"] %></span></h6>
          <% @total_quantity +=  cart["quantity"] %>
          <p><% @total_bill += product.price * cart["quantity"] %></p>
          <%= form_for :cart, url: cart_path(product.id), method: :patch, id: "update-cart", remote: true do |c| %>
            <div class="field">
              <%= c.number_field :addquantity, :value => cart["quantity"].to_i %>
            </div>
            <div class="field">
              <%= c.hidden_field :prod_price, value: product.price %>
            </div>
            <div class="field">
              <%= c.hidden_field :ttl_bill, value: @total_bill %>
            </div>
            <div class="actions">
              <%= c.submit "Update Quantity", style: 'color:white;', class: "btn btn-info"%>
            </div>
          <% end %>
          <h6>Total Bill: <span class="total_bill" data-id = "<%=product.id%>"><%= product.price * cart["quantity"]%></span></h6> <hr>
        </div>
        <div class="col-lg-4 d-flex align-items-center">
          <%= link_to 'Delete', cart_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        </div>
      </div><br>
      <%  @totl_crt += 1%>
      <% end -%>
    </div>
    <div class="col-lg-1"></div>
    <div class="col-lg-4" >
      <br>
      <h5> My Shopping Cart (<%= @totl_crt %> Items)</h5>
      <br>
      <h5>Total: <span style="color: orangered;" id="upd_bill">Rs. <%= @total_bill %>.00</span></h5>
      <%= link_to 'CHEACKOUT', orders_path(item: @total_quantity, bill: @total_bill), :method => "post", class: "btn btn-primary btn-lg buynow" %><br> <br>
      <%= link_to 'Shop More', root_path,  class: "btn btn-secondary btn-lg addcart" %>
    </div>
    <br>
  </div>
</div>

app/views/carts/index.js.erb
$('.cart_qty[data-id="<%= @product_id %>"]').html("<%= @order_quantity %>");
$('.total_bill[data-id="<%= @product_id %>"]').html('<%= @order_quantity * @prd_price %>')
$('#upd_bill').html('<%= @updtd_bill + (@updated_qty * @prd_price) %>')

//  $('#qty').html("<%= @ord_qty %>");  

app/views/carts/show.html.erb
<% if user_signed_in? %>
	<div class="container">
	  	<div class="row">
	  		<h5 style="color:green">One new Item has been added to your Cart</h5>
	  		<hr>
	  		<div class="col-lg-8">
	  			<div class="row">
	  				<div class="col-lg-3">
	  					<% if @product.avatars[0].nil? %>
	  					    <p>Image not available</p>
	  					<% else %>
	  					    <%= image_tag @product.avatars[0].url, size: '150x180' %>
	  					<% end %>
	  				</div>
	  				<div class="col-lg-9">
	  					<h3><%= @product.name %></h3><br>
	  					<h6 style="color:orangered;">Price: $<%= @product.price %>.00 only</h6><br>
	  					<h6>Quantity: </h6>
	  				</div>
	  			</div>
	  		</div>
	  		<div class="col-lg-4" style=" border-left: 6px solid green; height: auto;">
	  			<h5> My Shopping Cart (3 Items)</h5>
	  			<br>
	  			<h5>Total: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: orangered;">Rs. 333.00</span></h5>
	  			<%= link_to 'Go To Cart', carts_path,  class: "btn btn-primary btn-lg buynow" %>
	  			<%= link_to 'Shop More', root_path,  class: "btn btn-secondary btn-lg addcart" %>
	  		</div>
	  		<br>
	  		<hr>
	  	</div>
	</div>
  <% else %>
  <% user_session_path %>
<% end -%>

<%= link_to 'Delete', cart["product_id"], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>