config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'checkout/create'
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: "products#index"
  root to: "products#list"
  resources :products do
    resources :comments
    resources :reviews
  end
  mount ActionCable.server => '/cable'
  resources :carts
  resources :order_details
  resources :categories
  #resources :checkout
  post "checkout/create", to: "checkout#create"
  get "/search", to: "products#search"
  resources :orders
  resources :about 
  
end

app/models/article.rb
class Article < ApplicationRecord
	 belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5
  belongs_to :product
  belongs_to :user
  # after_create_commit { RenderCommentJob.perform_later self }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 6
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reviews
  has_many :order_details
  has_many :orders, :through => :order_details
  mount_uploaders :avatars, AvatarUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :orders
  has_many :comments
  has_many :reviews
  has_many :products
  enum user_type: {
    moderator: 0,
    buyer: 1
  }
  validates :name, :phone, :user_type, presence: true
  validates :phone, length: { maximum: 10 }
  validates :phone, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def index
		@categories = Category.all
    	authorize @categories
	end
	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
		authorize @category
	end

    def edit
	    @category = Category.find(params[:id])
    	authorize @category
	end

    def create
    	@category = Category.new(category_params)
    	authorize @category
	    if @category.save
	      redirect_to @category
	    else
	      render :new
	    end
    end
    def update
		@category = Category.find(params[:id])
		authorize @category 
		if @category.update(category_params)
		  redirect_to @category
		else
		  render 'edit'
		end
	end
    
    def destroy
		@category = Category.find(params[:id])
		authorize @category
		@category.destroy 
		redirect_to categories_path
	end

	private

    def category_params
        params.require(:category).permit(:name, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Add Category", style: 'color:white;', class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path, style: 'color:white;', class: "btn btn-info" %>
<br>

app/views/categories/index.html.erb
<table class="table table-bordered table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <% if policy(category).categ? %>
          <td><%= link_to 'Edit', edit_category_path(category), style: 'color:white;', class: "btn btn-info" %></td>
          <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, style: 'color:white;', class: "btn btn-info" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to 'New Category', new_category_path , style: 'color:white;', class: "btn btn-info"%>

app/views/categories/new.html.erb
<h1>Add A New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, style: 'color:white;', class: "btn btn-info" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category), style: 'color:white;', class: "btn btn-info" %> |
<%= link_to 'Back', new_product_path, style: 'color:white;', class: "btn btn-info" %>

<% if policy(@category).categ? %>
<%= link_to 'Back', categories_path, style: 'color:white;', class: "btn btn-info" %>
<% end %>