config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'checkout/create'
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: "products#index"
  root to: "products#list"
  resources :products do
    resources :comments
    resources :reviews
  end
  mount ActionCable.server => '/cable'
  resources :carts
  resources :order_details
  resources :categories
  #resources :checkout
  post "checkout/create", to: "checkout#create"
  get "/search", to: "products#search"
  resources :orders
  resources :about 
  
end

app/models/article.rb
class Article < ApplicationRecord
	 belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5
  belongs_to :product
  belongs_to :user
  # after_create_commit { RenderCommentJob.perform_later self }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 6
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reviews
  has_many :order_details
  has_many :orders, :through => :order_details
  mount_uploaders :avatars, AvatarUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :orders
  has_many :comments
  has_many :reviews
  has_many :products
  enum user_type: {
    moderator: 0,
    buyer: 1
  }
  validates :name, :phone, :user_type, presence: true
  validates :phone, length: { maximum: 10 }
  validates :phone, uniqueness: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
  def list
    @products = Product.page(params[:page])
  end

  def index
    @products = current_user.products
    authorize @products

	end

	def show
	  @product = Product.find(params[:id])
    @comment = Comment.new(product_id: @product.id)
    
	end

	def new
	  @product = Product.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    authorize @product
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    authorize @product
  end 

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:product][:category_id]
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end
    
    def destroy
    @product = Product.find(params[:id])
    @product.destroy 
    redirect_to products_path
  end

  def search
    if params[:search].blank?
      redirect_to root_path
    else
      @parameter = params[:search].downcase
      @results = Product.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end


  
    private
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :quantity, {avatars: []})
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
 
 <div class="field">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control", rows: "3" %>
  </div>
 
  <div class="field">
    <%= f.label :price, class: "form-label" %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= select_tag "product[category_id]", options_from_collection_for_select(Category.all, "id", "name"), prompt: "Select Category", class: "form-select form-select-lg mb-3" %>
  </div>

  <div class="field">
    <%= f.label :quantity, class: "form-label" %>
    <%= f.text_field :quantity, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= f.label :avatars, class: "form-label"%>
    <%= f.file_field :avatars, multiple: true, class: "form-control form-control-lg" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit", style: 'color:white;', class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Products</h1>

<%= render 'form' %>
<%= link_to 'Back', products_path, style: 'color:white;', class: "btn btn-info" %>

app/views/products/index.html.erb
<table class="table table-bordered table-striped table-condensed table-hover">
  <thead>
      <tr>
         <th>Name</th>
         <th>Description</th>
         <th>Price</th>
         <th>Category</th>
         <th>Quantity</th>
         <th colspan="3"></th>
      </tr>
  </thead>
 
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= link_to Category.find(product.category_id).name, category_path(product.category_id) %></td>
      <td><%= product.quantity %></td>
      <td><% if product.avatars[0].nil? %>
            <p>Image not available</p>
          <% else %>
            <%= image_tag product.avatars[0].url, size: '50x30' %>
          <% end %>
      </td>
      <td><%= link_to 'Show', product, style: 'color:white;', class: "btn btn-info" %></td>
      <td><%= link_to 'Edit', edit_product_path(product), style: 'color:white;', class: "btn btn-info" %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color:white;', class: "btn btn-info" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to 'New product', new_product_path, style: 'color:white;', class: "btn btn-info" %>

app/views/products/list.html.erb
<div class="container">
  <br>
  <div class="row">
    <% @products.each do |product| %>
    <% $avrg_rating = product.comments.average(:rating) %>
      <div class="col-lg-4">
        <div class="card" style="width: 18rem; border-style: solid; border-width: 1px; border-color: blue; color: black;">
          <div class="card-header" style="text-align: center;">
            <h5><%= product.name %></h5>
          </div>
          <div class="card-body">
            <% if product.avatars[0].nil? %>
              <p>Image not available</p>
            <% else %>
              <%= image_tag product.avatars[0].url, size: '250x280' %>
            <% end %>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><h5>Stock: <%= product.quantity %></h5></li>
              <li class="list-group-item"><h5>Price: <strong><%= product.price %>.00 $</strong></h5></li>
              <li class="list-group-item"><h5>Category: <%= Category.find(product.category_id).name%></h5></li>
              <li class="list-group-item">
                <div class="average-review-rating">
                </div>
              </li>
            </ul>
          </div>
          <div class="card-footer">
            <%= link_to 'Show', product, style: 'color:white;', class: "btn btn-danger" %>
          </div>
        </div>
        <br>
      </div>
      
    <% end %>
    <%= paginate @products %>
  </div>
</div>
<script>
   $(".average-review-rating").rateYo({
       rating: '<%= $averge_rating %>',
       spacing: "10px",
       numStars: 5,
       minValue: 0,
       maxValue: 5,
       normalFill: 'black',
       ratedFill: 'orange',
       readOnly: true
   });
</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Back', products_path, style: 'color:white;', class: "btn btn-info" %>

app/views/products/search.html.erb
<div class="container">
  <div class="row">
    <% @results.each do |product| %>
      <div class="col-lg-4">
        <div class="card" style="width: 18rem;">
          <div class="card-header">
            <h5><%= product.name %></h5>
          </div>
          <div class="card-body">
            <% if product.avatars[0].nil? %>
              <p>Image not available</p>
            <% else %>
              <%= image_tag product.avatars[0].url, size: '250x280' %>
            <% end %>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Stock: <%= product.quantity %></li>
              <li class="list-group-item">Price:<%= product.price %></li>
              <li class="list-group-item">Category: <%= link_to Category.find(product.category_id).name %></li>
              <li class="list-group-item">
                <div class="average-review-rating" data-score = "<%= product.comments.average(:rating) %>">
                </div>
              </li>
            </ul>
          </div>
          <div class="card-footer">
            <%= link_to 'Show', product, style: 'color:white;', class: "btn btn-danger" %>
          </div>
        </div>
        <br>
      </div>
      
    <% end %>
  </div>
</div>
<script>
  $('.average-review-rating').raty({
    readOnly: true,
    score: function() {
    return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/products/show.html.erb
<div class="container prod">
  <div class="row">
    <div class="col-lg-8">
      <div class="card" style="width: 37rem; border-style: solid; border-width: 1px; border-color: blue;">
        <div class="card-header" style="border-style: solid; border-width: 1px; border-color: blue; text-align: center; color: black;">
          <h2 style="color: orangered; font-family: sans-serif; font-weight: bold;"><%= @product.name %></h2>
        </div>
        <div class="bg-dark">
          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="d-flex justify-content-center">
                <% @product.avatars.each_with_index do |avatar, index| %>     
                  <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
                    <%= image_tag(avatar.url, size: '280x430') %>
                  </div>
                <% end %>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <div class="card-body">
          <h3 style="color: orangered;">Description:</h3>
          <h5><%= @product.description %></h5>
        </div>
        <div class="average-review-rating">
          <% $averge_rating = @product.comments.average(:rating) %>
        </div> <br>
      </div>  
    </div>
    <div class="col-lg-4">
      <div class="card" style="width: 19rem; border-style: solid; border-width: 1px; border-color: blue;">
        <div class="card-header" style="text-align: center; color: black;">
          <h2>Product Details</h2>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><h5 style="font-weight: bold;">Price: US $<%= @product.price %>.00 only</h5></li>
          <li class="list-group-item"> 
            <%= form_for :cart, url: carts_path do |c| %>
              <div class="field">
                <%= c.label :Quantity_Maximum, style: "font-weight: bold;" %>
                <%= c.number_field :addquantity, {min: 1, max: @product.quantity}%>
              </div>
              <div class="field">
                <%= c.hidden_field :product, value: @product.id %>
              </div>
              <div class="actions">
                <%= c.submit "Add To Cart",  style: 'color:white;', class: "btn btn-info" %>
              </div>
            <% end %>
          </li>
          <li class="list-group-item">
            <h4>Add a comment:</h4>
            <%= render 'comments/form' %>
          </li>
        </ul>
      </div>
      <div class="card border-success mb-3" style="max-width: 18rem;">
        <div class="card-header bg-transparent border-success">Comments</div>
        <div class="card-body text-success">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= render 'comments/comment' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if policy(@product).prod? %>
    <%= link_to 'Edit', edit_product_path(@product), style: 'color:white;', class: "btn btn-info" %> &nbsp;&nbsp;&nbsp;
    <%= link_to 'Your Products', products_path, style: 'color:white;', class: "btn btn-info" %> &nbsp;&nbsp;&nbsp;
  <% end %>
  <%= link_to 'All Products', root_path, style: 'color:white;', class: "btn btn-info" %>

</div>

<script>
   $(".average-review-rating").rateYo({
       rating: '<%= $averge_rating %>',
       spacing: "10px",
       numStars: 5,
       minValue: 0,
       maxValue: 5,
       normalFill: 'black',
       ratedFill: 'orange',
       readOnly: true
   });
</script>