config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'checkout/create'
  # devise_for :users, :controllers => { :registrations => 'users/registrations' }
  devise_for :users, :controllers => {:registrations => "users/registrations"}


  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: "products#index"
  root to: "products#list"
  resources :products do
    resources :comments
    resources :reviews
  end
  mount ActionCable.server => '/cable'
  resources :carts
  resources :order_details
  resources :categories
  #resources :checkout
  post "checkout/create", to: "checkout#create"
  get "/search", to: "products#search"
  resources :orders
  resources :about 
  
end

app/models/article.rb
class Article < ApplicationRecord
	 belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5
  belongs_to :product
  belongs_to :user
  # after_create_commit { RenderCommentJob.perform_later self }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 6
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reviews
  has_many :order_details
  has_many :orders, :through => :order_details
  mount_uploaders :avatars, AvatarUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :orders
  has_many :comments
  has_many :reviews
  has_many :products
  enum user_type: {
    moderator: 0,
    buyer: 1
  }
  validates :name, :phone, :user_type, presence: true
  validates :phone, length: { maximum: 10 }
  validates :phone, uniqueness: true
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white footer">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "facebook" %></i></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "twitter" %></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "google" %></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "instagram" %></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "linkedin" %></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><%= fa_icon "github" %></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-white" href="#"><%= link_to 'A-one Shopping', root_path, class: 'navbar-brand' %></a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#"><%= link_to image_tag("logos/online.png", size: '70x70', alt: "logo"), root_path, class: 'navbar-brand' %> </a>
    
    <div class="collapse navbar-collapse" id="navbarScroll">
      <div class="d-flex">
        <%= form_tag(search_path, :method => "get") do %>
          <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "Search Products....", class: "form-control me-2"%>
            <div class="input-group-btn">
              <%= button_tag "Search", class: "btn btn-outline-success" %>
            </div>
          </div>
        <% end %>
      </div>
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll " style="--bs-scroll-height: 100px;margin-left: auto;">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Product', new_product_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li> &nbsp; &nbsp; &nbsp;
          <li class="nav-item">
            <%= link_to 'Category', new_category_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li> &nbsp;&nbsp;&nbsp;
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, style: 'color:white;', method: :delete, class: "btn btn-secondary" %>
          </li> &nbsp; &nbsp; &nbsp;
          <li class="nav-item">
            <%= link_to 'Contact Us', about_index_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li>&nbsp;&nbsp;&nbsp;
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li>&nbsp;&nbsp;&nbsp;
          <li class="nav-item">
            <%= link_to 'Contact Us', about_index_path, style: 'color:white;', class: "btn btn-secondary" %>
          </li> 
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
 
<!DOCTYPE html>
<html>
  <head>
    <title>A-One Shopping</title>
    <%= csrf_meta_tags %>
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= action_cable_meta_tag %>
    <style type="text/css">
    </style>
  </head>
 
  <body>
    <%= render "layouts/navigation" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>